# SPDX-FileCopyrightText: 2022 Daniele Tentoni <daniele.tentoni.1996@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Check Reuse Compliance

on:
  pull_request:
    branches:
      - "main"

jobs:
  reuse-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1.1
