# SPDX-FileCopyrightText: 2022 Daniele Tentoni <daniele.tentoni.1996@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Produce Pandoc website

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1.1

      - name: Prepare repo
        run: mkdir dist

      - name: Create file list
        id: files_list
        run: echo "::set-output name=files::$(printf '"%s"\n' exam/*.md)"

      # pandoc exam/exam.md --from=markdown --to=html --output=dist/index.html --toc --template=elegant_bootstrap_menu.html --data-dir=.pandoc
      - name: Use Pandoc
        uses: docker://pandoc/minimal:2.18.0.0
        with:
          args: >-
            --data-dir=.pandoc
            --template=elegant_bootstrap_menu.html
            --toc
            --from=markdown
            --to=html
            --output=dist/index.html
            ${{ steps.files_list.outputs.files }}

      - uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: ./dist
      
  deploy:
    name: Deploy Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: convert_via_pandoc
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1